main: dev.mruniverse.pixelmotd.init.spigotPixelMOTD
name: PixelMOTD
version: 8.8.6-Alpha3
author: MrUniverse44
depend: [ProtocolLib]
description: Motd Plugin with RGB Support and Hover System.
commands:
  pmotd:
    description: PixelMOTD plugin short command.
  pixelmotd:
    description: PixelMOTD plugin command.
